### ISSUE TITLE
'SQS receive message failed: (0 , import_client.setCredentialFeature) is not a function'  When upgrading @aws-sdk/client-sqs@^3.858.0

### ISSUE THREAD

**Issue by minhle0908** [ssut/nestjs-sqs#101]
I got an error when upgrading the client to latest version of aws sdk. Its still working on 3.856.0. 
<img width="1211" height="219" alt="Image" src="https://github.com/user-attachments/assets/e3f09f37-bf2b-4bf3-b646-36697bf744e6" />
